/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.BanHang.jp_BanHang;
import View.HoaDon.jp_HoaDon;
import View.QuanLy.jp_QuanLy;
import View.ThongKe.jp_ThongKe;
import View.ThucDon.jp_ThucDon;
import java.awt.*;

/**
 *
 * @author NHT_Kurumi
 */
public class jf_TrangChu extends javax.swing.JFrame {

    jp_BanHang banhang;
    jp_ThucDon thucdon;
    jp_HoaDon hoadon;
    jp_QuanLy quanly;
    jp_ThongKe thongke;
    /**
     * Creates new form JFrameTrangChu
     */
    public jf_TrangChu() {
        initComponents();
        setTitle("Quản lý quán cà phê");
        setResizable(false);//Vô hiệu hóa nút phóng to     
//        getContentPane().setBackground(Color.WHITE);//Background đổi màu
        
        reloadPanel(1);
    }
    
    public void reloadPanel(int i) {
        jpView.removeAll();
        switch (i) {
            case 1:
                if (banhang == null) {
                    banhang = new jp_BanHang();
                } 
                jpView.add(banhang);
                break;
            case 2:
                if (thucdon == null) {
                    thucdon = new jp_ThucDon();
                }
                jpView.add(thucdon);
                break;
            case 3:
                if(hoadon == null){
                    hoadon = new jp_HoaDon();
                }
                jpView.add(hoadon);
                break;
            case 4:
                if(quanly == null){
                    quanly = new jp_QuanLy();
                }
                jpView.add(quanly);
                break;
            case 5:
                if(thongke == null){
                    thongke = new jp_ThongKe();
                }
                jpView.add(thongke);
                break;
            default:
                break;
        }
        jpView.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHome = new javax.swing.JPanel();
        btBanHang = new javax.swing.JButton();
        jpView = new javax.swing.JPanel();
        btThucDon = new javax.swing.JButton();
        btHoaDon = new javax.swing.JButton();
        btQuanLy = new javax.swing.JButton();
        btThongKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(185, 94, 27));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpHome.setBackground(new java.awt.Color(185, 94, 27));
        jpHome.setPreferredSize(new java.awt.Dimension(1350, 58));

        btBanHang.setBackground(new java.awt.Color(139, 69, 19));
        btBanHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btBanHang.setForeground(new java.awt.Color(255, 255, 255));
        btBanHang.setText("BÁN HÀNG");
        btBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBanHangActionPerformed(evt);
            }
        });

        jpView.setBackground(new java.awt.Color(255, 255, 255));
        jpView.setPreferredSize(new java.awt.Dimension(1350, 744));
        jpView.setLayout(new java.awt.BorderLayout());

        btThucDon.setBackground(new java.awt.Color(185, 94, 27));
        btThucDon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btThucDon.setForeground(new java.awt.Color(255, 255, 255));
        btThucDon.setText("THỰC ĐƠN");
        btThucDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThucDonActionPerformed(evt);
            }
        });

        btHoaDon.setBackground(new java.awt.Color(185, 94, 27));
        btHoaDon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btHoaDon.setText("HÓA ĐƠN");
        btHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoaDonActionPerformed(evt);
            }
        });

        btQuanLy.setBackground(new java.awt.Color(185, 94, 27));
        btQuanLy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btQuanLy.setForeground(new java.awt.Color(255, 255, 255));
        btQuanLy.setText("QUẢN LÝ");
        btQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuanLyActionPerformed(evt);
            }
        });

        btThongKe.setBackground(new java.awt.Color(185, 94, 27));
        btThongKe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btThongKe.setText("THỐNG KÊ");
        btThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHomeLayout = new javax.swing.GroupLayout(jpHome);
        jpHome.setLayout(jpHomeLayout);
        jpHomeLayout.setHorizontalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHomeLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(btBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpHomeLayout.createSequentialGroup()
                .addComponent(jpView, javax.swing.GroupLayout.PREFERRED_SIZE, 1800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpHomeLayout.setVerticalGroup(
            jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHomeLayout.createSequentialGroup()
                .addGroup(jpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThucDon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jpView, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpHome, javax.swing.GroupLayout.PREFERRED_SIZE, 1800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpHome, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBanHangActionPerformed
        reloadPanel(1);
    }//GEN-LAST:event_btBanHangActionPerformed

    private void btThucDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThucDonActionPerformed
        reloadPanel(2);
    }//GEN-LAST:event_btThucDonActionPerformed

    private void btHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoaDonActionPerformed
        reloadPanel(3);
    }//GEN-LAST:event_btHoaDonActionPerformed

    private void btQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuanLyActionPerformed
        reloadPanel(4);
    }//GEN-LAST:event_btQuanLyActionPerformed

    private void btThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongKeActionPerformed
        reloadPanel(5);
    }//GEN-LAST:event_btThongKeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Viền btBanHang
        btBanHang.setBorderPainted(false);
        btBanHang.setContentAreaFilled(false);
        btBanHang.setFocusPainted(false);
        btBanHang.setOpaque(false);
        //Viền btThucDon
        btThucDon.setBorderPainted(false);
        btThucDon.setContentAreaFilled(false);
        btThucDon.setFocusPainted(false);
        btThucDon.setOpaque(false);
        //Viền btHoaDon
        btHoaDon.setBorderPainted(false);
        btHoaDon.setContentAreaFilled(false);
        btHoaDon.setFocusPainted(false);
        btHoaDon.setOpaque(false);
        //Viền btQuanLy
        btQuanLy.setBorderPainted(false);
        btQuanLy.setContentAreaFilled(false);
        btQuanLy.setFocusPainted(false);
        btQuanLy.setOpaque(false);
        //Viền btThongKe
        btThongKe.setBorderPainted(false);
        btThongKe.setContentAreaFilled(false);
        btThongKe.setFocusPainted(false);
        btThongKe.setOpaque(false);
        //Viền 
//        jbtThoat.setBorderPainted(false);
//        jbtThoat.setContentAreaFilled(false);
//        jbtThoat.setFocusPainted(false);
//        jbtThoat.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBanHang;
    private javax.swing.JButton btHoaDon;
    private javax.swing.JButton btQuanLy;
    private javax.swing.JButton btThongKe;
    private javax.swing.JButton btThucDon;
    private javax.swing.JPanel jpHome;
    private javax.swing.JPanel jpView;
    // End of variables declaration//GEN-END:variables
}
